import { Platform, StyleSheet } from 'react-native';

import { accent, bg, gold, ink, muted, panel } from './theme';

const shadowText = (shadow: string, color: string, height = 1, radius = 7) =>
  Platform.select({
    web: { textShadow: shadow },
    default: {
      textShadowColor: color,
      textShadowOffset: { width: 0, height },
      textShadowRadius: radius,
    },
  });

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: bg,
    ...Platform.select({
      web: { minHeight: '100vh' },
      default: {},
    }),
  },
  app: {
    alignSelf: 'center',
    flex: 1,
    backgroundColor: bg,
    maxWidth: 760,
    width: '100%',
  },
  appCompact: {
    maxWidth: '100%',
  },
  appTablet: {
    maxWidth: 900,
  },
  appDesktop: {
    maxWidth: 1280,
    ...Platform.select({
      web: { minHeight: '100vh' },
      default: {},
    }),
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 10,
  },
  headerCompact: {
    paddingHorizontal: 12,
  },
  headerDesktop: {
    paddingLeft: 148,
    paddingRight: 28,
    paddingTop: 34,
  },
  eyebrow: {
    color: accent,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: ink,
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: 3,
  },
  titleCompact: {
    fontSize: 22,
    lineHeight: 27,
  },
  headerActions: {
    flexDirection: 'row',
    flexShrink: 0,
    gap: 10,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  content: {
    paddingHorizontal: 14,
    paddingBottom: 102,
    paddingTop: 8,
  },
  contentCompact: {
    paddingHorizontal: 10,
  },
  contentDesktop: {
    paddingBottom: 36,
    paddingHorizontal: 28,
    paddingLeft: 148,
    paddingTop: 20,
  },
  routeFallback: {
    alignItems: 'center',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 240,
    padding: 22,
  },
  routeFallbackText: {
    color: ink,
    fontSize: 22,
    fontWeight: '900',
    marginTop: 8,
  },
  onboarding: {
    alignSelf: 'center',
    backgroundColor: bg,
    flexGrow: 1,
    justifyContent: 'center',
    maxWidth: 760,
    padding: 22,
    width: '100%',
  },
  onboardingBrand: {
    color: accent,
    fontSize: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  onboardingTitle: {
    color: ink,
    fontSize: 39,
    fontWeight: '900',
    lineHeight: 43,
    marginTop: 10,
  },
  onboardingBody: {
    color: muted,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 23,
    marginTop: 12,
  },
  onboardingSection: {
    color: ink,
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 10,
    marginTop: 24,
  },
  onboardingChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  onboardingChip: {
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  onboardingChipActive: {
    backgroundColor: gold,
    borderColor: gold,
  },
  onboardingChipText: {
    color: ink,
    fontSize: 13,
    fontWeight: '900',
  },
  onboardingChipTextActive: {
    color: bg,
  },
  onboardingChoice: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  onboardingButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 26,
    minHeight: 54,
  },
  onboardingButtonText: {
    color: bg,
    fontSize: 15,
    fontWeight: '900',
  },
  authPage: {
    alignItems: 'center',
    backgroundColor: bg,
    flexGrow: 1,
    justifyContent: 'center',
    padding: 22,
  },
  authPageDesktop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 56,
    justifyContent: 'center',
    minHeight: 760,
    paddingHorizontal: 64,
    paddingTop: 56,
  },
  authIntro: {
    maxWidth: 430,
    width: '100%',
  },
  authIntroDesktop: {
    maxWidth: 480,
  },
  authBrand: {
    color: accent,
    fontSize: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  authTitle: {
    color: ink,
    fontSize: 40,
    fontWeight: '900',
    lineHeight: 44,
    marginTop: 10,
  },
  authTitleDesktop: {
    fontSize: 58,
    lineHeight: 62,
  },
  authBody: {
    color: muted,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 23,
    marginTop: 12,
  },
  authDesktopStats: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 28,
  },
  authFormColumn: {
    maxWidth: 430,
    width: '100%',
  },
  authCard: {
    backgroundColor: panel,
    borderRadius: 8,
    marginTop: 26,
    maxWidth: 430,
    padding: 14,
    width: '100%',
  },
  authCardDesktop: {
    marginTop: 0,
  },
  authProviderButton: {
    alignItems: 'center',
    backgroundColor: '#f4f5ef',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    marginBottom: 10,
    paddingHorizontal: 14,
  },
  authProviderMark: {
    color: bg,
    fontSize: 16,
    fontWeight: '900',
    width: 20,
  },
  authProviderText: {
    color: bg,
    fontSize: 14,
    fontWeight: '900',
  },
  authDivider: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginVertical: 8,
  },
  authDividerLine: {
    backgroundColor: '#34392e',
    flex: 1,
    height: 1,
  },
  authDividerText: {
    color: muted,
    fontSize: 12,
    fontWeight: '900',
  },
  fakeInput: {
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    padding: 12,
  },
  fakeInputLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  fakeInputValue: {
    color: ink,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 6,
  },
  authInput: {
    color: ink,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 6,
    minHeight: 26,
    padding: 0,
  },
  authPrimaryButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 52,
  },
  authPrimaryButtonDisabled: {
    opacity: 0.45,
  },
  forgotPassword: {
    alignItems: 'center',
    marginTop: 12,
    padding: 6,
  },
  forgotPasswordText: {
    color: gold,
    fontSize: 13,
    fontWeight: '900',
  },
  authError: {
    color: '#ffb4a8',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 6,
  },
  authHelper: {
    color: muted,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
    marginTop: 8,
    textAlign: 'center',
  },
  authPrimaryText: {
    color: bg,
    fontSize: 15,
    fontWeight: '900',
  },
  authSwitch: {
    alignItems: 'center',
    marginTop: 18,
    padding: 8,
  },
  authSwitchText: {
    color: gold,
    fontSize: 14,
    fontWeight: '900',
  },
  segment: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  segmentActive: {
    backgroundColor: '#252820',
    borderRadius: 18,
    color: gold,
    fontSize: 13,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  segmentMuted: {
    color: muted,
    fontSize: 13,
    fontWeight: '800',
    paddingHorizontal: 8,
  },
  detailBack: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    paddingVertical: 4,
  },
  detailBackText: {
    color: ink,
    fontSize: 13,
    fontWeight: '900',
  },
  detailHero: {
    height: 320,
    marginBottom: 12,
  },
  detailHeroImage: {
    borderRadius: 8,
  },
  detailShade: {
    backgroundColor: 'rgba(0,0,0,0.48)',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'flex-end',
    padding: 18,
  },
  detailMeta: {
    color: gold,
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  detailTitle: {
    color: '#fff',
    fontSize: 36,
    fontWeight: '900',
    lineHeight: 40,
  },
  detailBody: {
    color: ink,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 21,
    marginTop: 12,
  },
  detailActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  continueButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 52,
  },
  continueText: {
    color: bg,
    fontSize: 15,
    fontWeight: '900',
  },
  detailIconButton: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    justifyContent: 'center',
    width: 54,
  },
  detailProgressCard: {
    backgroundColor: panel,
    borderRadius: 8,
    padding: 14,
  },
  showListPanel: {
    backgroundColor: panel,
    borderColor: '#303428',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    marginBottom: 12,
    padding: 14,
  },
  detailRetryButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 44,
    paddingHorizontal: 16,
  },
  detailRetryText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  detailSmallLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  detailProgressValue: {
    color: ink,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 3,
  },
  timeline: {
    backgroundColor: panel,
    borderRadius: 8,
    padding: 12,
  },
  seasonTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  seasonTab: {
    backgroundColor: panel,
    borderRadius: 16,
    color: muted,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  seasonTabActive: {
    backgroundColor: gold,
    color: bg,
  },
  seasonSummary: {
    alignItems: 'center',
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 12,
  },
  seasonSummaryText: {
    color: ink,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  timelineItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 54,
  },
  timelineDot: {
    alignItems: 'center',
    backgroundColor: '#34392e',
    borderRadius: 13,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  timelineDotDone: {
    backgroundColor: accent,
  },
  timelineCopy: {
    borderBottomColor: '#252820',
    borderBottomWidth: 1,
    flex: 1,
    paddingBottom: 10,
    paddingTop: 10,
  },
  timelineCode: {
    color: gold,
    fontSize: 11,
    fontWeight: '900',
  },
  timelineTitle: {
    color: ink,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 3,
  },
  timelineRatingBadge: {
    alignItems: 'center',
    backgroundColor: '#252820',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 3,
    marginLeft: 8,
    minHeight: 24,
    paddingHorizontal: 7,
  },
  communityCard: {
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  communityMetric: {
    alignItems: 'center',
    backgroundColor: '#11130f',
    borderRadius: 8,
    flex: 1,
    minHeight: 96,
    justifyContent: 'center',
  },
  communityValue: {
    color: ink,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 8,
  },
  communityLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 3,
    textTransform: 'uppercase',
  },
  movieCard: {
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 172,
    marginBottom: 12,
    overflow: 'hidden',
  },
  movieLockedHero: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 18,
    padding: 22,
  },
  movieLockIcon: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    marginBottom: 14,
    width: 48,
  },
  movieLockedTitle: {
    color: ink,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  movieLockedBody: {
    color: muted,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 21,
    marginTop: 10,
    textAlign: 'center',
  },
  movieLockedBadge: {
    alignItems: 'center',
    borderColor: gold,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  movieLockedBadgeText: {
    color: ink,
    fontSize: 12,
    fontWeight: '900',
  },
  supportUsButton: {
    alignItems: 'center',
    backgroundColor: gold,
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 46,
    paddingHorizontal: 18,
    width: '100%',
  },
  supportUsText: {
    color: bg,
    fontSize: 14,
    fontWeight: '900',
  },
  moviePoster: {
    alignSelf: 'stretch',
    width: 116,
  },
  moviePosterImage: {
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
  },
  movieCardCopy: {
    flex: 1,
    justifyContent: 'center',
    padding: 14,
  },
  movieTitle: {
    color: ink,
    fontSize: 21,
    fontWeight: '900',
  },
  movieMeta: {
    color: gold,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 5,
  },
  movieBody: {
    color: '#d7dccf',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 10,
  },
  movieFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  movieDetailHero: {
    height: 380,
    marginBottom: 12,
  },
  movieDetailStats: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  movieListPicker: {
    gap: 8,
  },
  movieListOption: {
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  movieListOptionActive: {
    borderColor: gold,
  },
  movieListOptionText: {
    color: muted,
    fontSize: 13,
    fontWeight: '900',
  },
  movieListOptionTextActive: {
    color: ink,
  },
  movieCardPreview: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 14,
    padding: 14,
  },
  movieCardScore: {
    alignItems: 'center',
    backgroundColor: '#11130f',
    borderRadius: 8,
    height: 82,
    justifyContent: 'center',
    width: 82,
  },
  movieScoreValue: {
    color: ink,
    fontSize: 21,
    fontWeight: '900',
    marginTop: 5,
  },
  episodeCard: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 130,
    marginBottom: 12,
    overflow: 'hidden',
    paddingRight: 12,
  },
  episodeCardCompact: {
    minHeight: 116,
    paddingRight: 8,
  },
  poster: {
    alignSelf: 'stretch',
    width: 104,
  },
  episodeBody: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  episodeBodyCompact: {
    paddingHorizontal: 10,
  },
  pill: {
    alignSelf: 'flex-start',
    borderColor: '#d9ded1',
    borderRadius: 14,
    borderWidth: 1,
    color: ink,
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 8,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
  code: {
    color: ink,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0,
  },
  episodeTitle: {
    color: '#d7dccf',
    fontSize: 15,
    fontWeight: '600',
    marginTop: 3,
  },
  episodeTitleCompact: {
    fontSize: 14,
    lineHeight: 19,
  },
  progressRail: {
    backgroundColor: '#34392e',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 3,
    height: 18,
    marginTop: 12,
    overflow: 'hidden',
    padding: 4,
    position: 'relative',
  },
  progressGlow: {
    backgroundColor: accent,
    bottom: 0,
    left: 0,
    opacity: 0.18,
    position: 'absolute',
    top: 0,
  },
  progressSegment: {
    backgroundColor: '#53594b',
    borderRadius: 4,
    flex: 1,
    height: 10,
  },
  progressSegmentWatched: {
    backgroundColor: accent,
  },
  progressSegmentLast: {
    marginRight: 0,
  },
  cardFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  cardTag: {
    color: muted,
    fontSize: 10,
    fontWeight: '900',
  },
  progressText: {
    color: '#d7dccf',
    fontSize: 11,
    fontWeight: '900',
  },
  checkCircle: {
    alignItems: 'center',
    backgroundColor: '#f4f5ef',
    borderRadius: 28,
    flexShrink: 0,
    height: 56,
    marginLeft: 6,
    justifyContent: 'center',
    width: 56,
  },
  checkCircleCompact: {
    height: 46,
    width: 46,
  },
  checkCircleDone: {
    backgroundColor: accent,
  },
  ratingText: {
    color: ink,
    fontSize: 11,
    fontWeight: '900',
  },
  queueHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  queueKicker: {
    color: gold,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  queueTitle: {
    color: ink,
    fontSize: 22,
    fontWeight: '900',
    marginTop: 2,
  },
  matchBadge: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  matchText: {
    color: bg,
    fontSize: 12,
    fontWeight: '900',
  },
  heroQueue: {
    height: 430,
    marginBottom: 14,
  },
  heroQueueCompact: {
    height: 370,
  },
  heroQueueImage: {
    borderRadius: 8,
  },
  heroShade: {
    backgroundColor: 'rgba(0,0,0,0.42)',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'flex-end',
    padding: 18,
  },
  fitRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  fitBadge: {
    backgroundColor: 'rgba(8,9,8,0.72)',
    borderColor: 'rgba(247,249,242,0.24)',
    borderRadius: 15,
    borderWidth: 1,
    color: '#e8ecd9',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroTitle: {
    color: '#fff',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
    ...shadowText('0 2px 8px rgba(0,0,0,0.72)', 'rgba(0,0,0,0.72)', 2, 8),
  },
  heroTitleCompact: {
    fontSize: 28,
    lineHeight: 32,
  },
  heroMeta: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(8,9,8,0.68)',
    borderColor: 'rgba(247,249,242,0.26)',
    borderRadius: 8,
    borderWidth: 1,
    color: '#e8ecd9',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 6,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
    ...shadowText('0 1px 6px rgba(0,0,0,0.7)', 'rgba(0,0,0,0.7)', 1, 6),
  },
  heroBody: {
    backgroundColor: 'rgba(8,9,8,0.66)',
    borderColor: 'rgba(247,249,242,0.22)',
    borderRadius: 8,
    borderWidth: 1,
    color: ink,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    marginTop: 14,
    overflow: 'hidden',
    padding: 12,
    ...shadowText('0 1px 7px rgba(0,0,0,0.78)', 'rgba(0,0,0,0.78)'),
  },
  heroReason: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(8,9,8,0.76)',
    borderColor: gold,
    borderRadius: 8,
    borderWidth: 1,
    color: gold,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 19,
    marginTop: 12,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 7,
    ...shadowText('0 1px 7px rgba(0,0,0,0.82)', 'rgba(0,0,0,0.82)'),
  },
  queueActions: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  queueAction: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flex: 1,
    gap: 6,
    justifyContent: 'center',
    minHeight: 70,
  },
  queueActionPrimary: {
    backgroundColor: accent,
  },
  queueActionText: {
    color: ink,
    fontSize: 12,
    fontWeight: '900',
  },
  queueActionPrimaryText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  nextRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  nextRailCompact: {
    flexDirection: 'column',
  },
  nextCard: {
    backgroundColor: panel,
    borderRadius: 8,
    flex: 1,
    overflow: 'hidden',
  },
  nextCardCompact: {
    flex: undefined,
  },
  nextPoster: {
    height: 112,
  },
  nextPosterImage: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  nextTitle: {
    color: ink,
    fontSize: 14,
    fontWeight: '900',
    marginHorizontal: 10,
    marginTop: 10,
  },
  nextMeta: {
    color: muted,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 12,
    marginHorizontal: 10,
    marginTop: 4,
  },
  identityHeader: {
    alignItems: 'center',
    paddingBottom: 18,
    paddingTop: 8,
    position: 'relative',
  },
  profileSettingsButton: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 4,
    width: 42,
  },
  identityCopy: {
    alignItems: 'center',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 36,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  profileName: {
    color: ink,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 12,
    textAlign: 'center',
  },
  personaBadge: {
    alignItems: 'center',
    backgroundColor: gold,
    borderRadius: 16,
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    minHeight: 30,
    paddingHorizontal: 11,
  },
  personaText: {
    color: bg,
    fontSize: 12,
    fontWeight: '900',
  },
  watchPanel: {
    alignItems: 'center',
    marginHorizontal: 'auto',
    marginTop: 14,
    maxWidth: 430,
    width: '100%',
  },
  watchStats: {
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    padding: 10,
    width: '100%',
  },
  preferenceSummary: {
    backgroundColor: panel,
    borderRadius: 8,
    gap: 8,
    padding: 14,
  },
  preferenceSummaryText: {
    color: ink,
    fontSize: 13,
    fontWeight: '800',
  },
  miniStat: {
    backgroundColor: panel,
    borderRadius: 8,
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  miniStatValue: {
    color: ink,
    fontSize: 20,
    fontWeight: '900',
  },
  miniStatLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  achievementShelf: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  activityList: {
    backgroundColor: panel,
    borderRadius: 8,
    overflow: 'hidden',
  },
  activityItem: {
    alignItems: 'center',
    borderBottomColor: '#252820',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
    padding: 12,
  },
  activityDot: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  activityCopy: {
    flex: 1,
    minWidth: 0,
  },
  activityTitle: {
    color: ink,
    fontSize: 14,
    fontWeight: '900',
  },
  activitySubtitle: {
    color: muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  activityTime: {
    color: muted,
    fontSize: 11,
    fontWeight: '900',
  },
  activityEmpty: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 86,
    padding: 16,
  },
  activityEmptyText: {
    color: muted,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  achievementEmpty: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 112,
    padding: 16,
  },
  achievementEmptyText: {
    color: muted,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  achievement: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    minHeight: 112,
    padding: 12,
    width: 112,
  },
  achievementIcon: {
    alignItems: 'center',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  achievementText: {
    color: ink,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 16,
    marginTop: 10,
    textAlign: 'center',
  },
  posterSpine: {
    flexDirection: 'row',
    gap: 8,
    height: 186,
  },
  spinePoster: {
    flex: 1,
  },
  spinePosterImage: {
    borderRadius: 8,
  },
  spineShade: {
    backgroundColor: 'rgba(0,0,0,0.28)',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'flex-end',
    padding: 8,
  },
  spineTitle: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 13,
  },
  sectionTitle: {
    color: ink,
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 10,
    marginTop: 22,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    marginTop: 12,
    padding: 28,
  },
  emptyVisual: {
    alignItems: 'center',
    height: 74,
    justifyContent: 'center',
    marginBottom: 4,
    position: 'relative',
    width: 104,
  },
  emptyPosterGhost: {
    backgroundColor: '#252820',
    borderColor: '#34392e',
    borderRadius: 8,
    borderWidth: 1,
    height: 64,
    left: 14,
    position: 'absolute',
    transform: [{ rotate: '-7deg' }],
    width: 44,
  },
  emptyPosterGhostSmall: {
    backgroundColor: '#1c2018',
    borderColor: '#34392e',
    borderRadius: 8,
    borderWidth: 1,
    height: 56,
    position: 'absolute',
    right: 14,
    transform: [{ rotate: '8deg' }],
    width: 40,
  },
  emptyIconWrap: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  emptyTitle: {
    color: ink,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 14,
  },
  emptyBody: {
    color: muted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    textAlign: 'center',
  },
  emptyAction: {
    backgroundColor: gold,
    borderRadius: 8,
    marginTop: 16,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  emptyActionText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  nav: {
    alignItems: 'center',
    backgroundColor: '#050605',
    borderTopColor: '#20231d',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    height: 82,
    justifyContent: 'space-around',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  navDesktop: {
    alignItems: 'stretch',
    borderRightColor: '#20231d',
    borderRightWidth: 1,
    borderTopWidth: 0,
    bottom: 0,
    flexDirection: 'column',
    gap: 12,
    height: '100%',
    justifyContent: 'flex-start',
    left: 0,
    paddingHorizontal: 8,
    paddingTop: 126,
    paddingVertical: 0,
    right: undefined,
    top: 0,
    width: 116,
  },
  navItem: {
    alignItems: 'center',
    gap: 5,
    justifyContent: 'center',
    minWidth: 64,
  },
  navItemDesktop: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    height: 46,
    justifyContent: 'flex-start',
    minWidth: 0,
    paddingHorizontal: 8,
    width: '100%',
  },
  navItemDesktopActive: {
    backgroundColor: '#11130f',
  },
  navLabel: {
    color: '#71808a',
    fontSize: 11,
    fontWeight: '800',
  },
  navLabelDesktop: {
    fontSize: 12,
  },
  navLabelActive: {
    color: accent,
  },
  reactionHero: {
    height: 280,
    marginBottom: 12,
  },
  reactionHeroImage: {
    borderRadius: 8,
  },
  reactionShade: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'flex-end',
    padding: 18,
  },
  reactionShow: {
    color: '#fff',
    fontSize: 31,
    fontWeight: '900',
    lineHeight: 35,
  },
  reactionEpisode: {
    color: '#e8ecd9',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 7,
  },
  watchedStamp: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: accent,
    borderRadius: 16,
    flexDirection: 'row',
    gap: 6,
    marginTop: 14,
    minHeight: 32,
    paddingHorizontal: 11,
  },
  watchedStampText: {
    color: bg,
    fontSize: 12,
    fontWeight: '900',
  },
  reactionPanel: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    padding: 18,
  },
  reactionSectionLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  reactionStars: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 12,
  },
  reactionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  reactionChip: {
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  reactionChipActive: {
    backgroundColor: gold,
    borderColor: gold,
  },
  reactionChipText: {
    color: ink,
    fontSize: 13,
    fontWeight: '900',
  },
  reactionChipActiveText: {
    color: bg,
  },
  characterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  characterPill: {
    backgroundColor: panel,
    borderRadius: 18,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  characterPillActive: {
    backgroundColor: accent,
  },
  characterText: {
    color: ink,
    fontSize: 13,
    fontWeight: '900',
  },
  characterTextActive: {
    color: bg,
  },
  reactionNoteInput: {
    backgroundColor: panel,
    borderColor: '#303428',
    borderRadius: 8,
    borderWidth: 1,
    color: ink,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    minHeight: 96,
    padding: 12,
    textAlignVertical: 'top',
  },
  reactionSaveMessage: {
    color: gold,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 14,
    textAlign: 'center',
  },
  commentsPreview: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  commentsCopy: {
    flex: 1,
  },
  commentsTitle: {
    color: ink,
    fontSize: 15,
    fontWeight: '900',
  },
  commentsBody: {
    color: muted,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 3,
  },
  saveReactionButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 52,
  },
  saveReactionText: {
    color: bg,
    fontSize: 14,
    fontWeight: '900',
  },
  communityHero: {
    height: 250,
    marginBottom: 12,
  },
  communitySummary: {
    flexDirection: 'row',
    gap: 8,
  },
  spoilerLock: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    marginTop: 14,
    padding: 22,
  },
  spoilerLockTitle: {
    color: ink,
    fontSize: 19,
    fontWeight: '900',
    marginTop: 12,
  },
  spoilerLockBody: {
    color: muted,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 8,
    textAlign: 'center',
  },
  commentList: {
    gap: 10,
  },
  commentComposer: {
    backgroundColor: panel,
    borderColor: '#303428',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 18,
    padding: 14,
  },
  commentInput: {
    backgroundColor: '#11140f',
    borderColor: '#34392e',
    borderRadius: 8,
    borderWidth: 1,
    color: ink,
    fontSize: 14,
    fontWeight: '700',
    minHeight: 92,
    padding: 12,
    textAlignVertical: 'top',
  },
  commentMoodRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commentMoodChip: {
    backgroundColor: '#11140f',
    borderColor: '#34392e',
    borderRadius: 999,
    borderWidth: 1,
    color: muted,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  commentMoodChipActive: {
    backgroundColor: gold,
    borderColor: gold,
    color: bg,
  },
  commentError: {
    color: '#ff8a8a',
    fontSize: 12,
    fontWeight: '800',
  },
  commentSubmit: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: accent,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 14,
  },
  commentSubmitDisabled: {
    opacity: 0.45,
  },
  commentSubmitText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  commentCard: {
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  commentAvatar: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  commentAvatarText: {
    color: bg,
    fontSize: 16,
    fontWeight: '900',
  },
  commentCopy: {
    flex: 1,
  },
  commentTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  commentUser: {
    color: ink,
    fontSize: 15,
    fontWeight: '900',
  },
  commentMood: {
    color: gold,
    fontSize: 11,
    fontWeight: '900',
  },
  commentText: {
    color: '#d7dccf',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 7,
  },
  commentLikes: {
    color: muted,
    fontSize: 11,
    fontWeight: '900',
    marginTop: 9,
  },
  searchBox: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 54,
    paddingHorizontal: 14,
  },
  searchPlaceholder: {
    color: muted,
    fontSize: 15,
    fontWeight: '700',
  },
  searchInput: {
    color: ink,
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    minHeight: 38,
  },
  searchScreen: {
    position: 'relative',
  },
  searchSuggestionPanel: {
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 12,
    padding: 10,
  },
  searchFeedbackOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.58)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    opacity: 1,
    position: 'absolute',
    right: 0,
    top: 0,
    transitionDuration: '520ms',
    transitionProperty: 'opacity',
    zIndex: 50,
  },
  searchFeedbackOverlayLeaving: {
    opacity: 0,
  },
  searchFeedback: {
    alignItems: 'center',
    backgroundColor: '#182014',
    borderColor: '#6f9c2f',
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 18px 42px rgba(0, 0, 0, 0.34)',
    maxWidth: 320,
    opacity: 1,
    padding: 22,
    transform: 'scale(1)',
    transitionDuration: '520ms',
    transitionProperty: 'opacity, transform',
    width: '82%',
  },
  searchFeedbackIcon: {
    alignItems: 'center',
    backgroundColor: '#6f9c2f',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    marginBottom: 14,
    width: 56,
  },
  searchFeedbackLeaving: {
    opacity: 0,
    transform: 'scale(0.96)',
  },
  searchFeedbackTitle: {
    color: '#f8f8f9',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  searchFeedbackText: {
    color: '#b8c1ad',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 6,
    textAlign: 'center',
  },
  searchSuggestion: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 9,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  searchSuggestionText: {
    color: ink,
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
  },
  searchFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    marginTop: 12,
  },
  searchFilter: {
    backgroundColor: panel,
    borderRadius: 16,
    color: muted,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  searchFilterActive: {
    backgroundColor: gold,
    color: bg,
  },
  platformFilterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  platformFilterCard: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 48,
    minWidth: 128,
    paddingHorizontal: 12,
  },
  platformFilterCardActive: {
    backgroundColor: gold,
    borderColor: gold,
  },
  platformFilterText: {
    color: ink,
    fontSize: 13,
    fontWeight: '900',
  },
  platformFilterTextActive: {
    color: bg,
  },
  recentSearches: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  recentChip: {
    borderColor: '#34392e',
    borderRadius: 17,
    borderWidth: 1,
    color: ink,
    fontSize: 13,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  trendingSearches: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  trendingChip: {
    alignItems: 'center',
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  trendingRank: {
    color: gold,
    fontSize: 12,
    fontWeight: '900',
  },
  trendingText: {
    color: ink,
    fontSize: 13,
    fontWeight: '800',
  },
  actorPreview: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
    padding: 12,
    position: 'relative',
  },
  actorPreviewImage: {
    height: 72,
    width: 56,
  },
  actorPreviewImageStyle: {
    borderRadius: 8,
  },
  actorPreviewCopy: {
    flex: 1,
  },
  actorPreviewKicker: {
    color: gold,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  actorPreviewTitle: {
    color: ink,
    fontSize: 17,
    fontWeight: '900',
    marginTop: 3,
  },
  actorPreviewBody: {
    color: muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 4,
  },
  actorPreviewClose: {
    alignItems: 'center',
    backgroundColor: '#252820',
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  resultsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  viewToggle: {
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    padding: 4,
  },
  viewToggleText: {
    borderRadius: 6,
    color: muted,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  viewToggleTextActive: {
    backgroundColor: gold,
    color: bg,
  },
  searchResults: {
    gap: 10,
  },
  searchGridResults: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  searchGridCard: {
    backgroundColor: panel,
    borderRadius: 8,
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: 238,
    overflow: 'hidden',
  },
  searchGridPoster: {
    height: 132,
  },
  searchGridPosterImage: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  searchResultCard: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 96,
    overflow: 'hidden',
  },
  searchPoster: {
    alignSelf: 'stretch',
    width: 72,
  },
  searchPosterImage: {
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
  },
  searchResultCopy: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 12,
  },
  searchResultTitle: {
    color: ink,
    fontSize: 17,
    fontWeight: '900',
  },
  searchResultMeta: {
    color: muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 4,
  },
  searchAddButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    marginRight: 12,
    width: 42,
  },
  searchLockedButton: {
    opacity: 0.7,
  },
  searchPremiumPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: gold,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  searchPremiumText: {
    color: gold,
    fontSize: 11,
    fontWeight: '900',
  },
  searchAddedButton: {
    backgroundColor: gold,
  },
  calendarHero: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  calendarKicker: {
    color: gold,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  calendarTitle: {
    color: ink,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 3,
  },
  calendarBadge: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  calendarBadgeText: {
    color: bg,
    fontSize: 12,
    fontWeight: '900',
  },
  calendarDays: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  calendarDayPill: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flex: 1,
    minHeight: 64,
    justifyContent: 'center',
  },
  calendarDayPillActive: {
    backgroundColor: gold,
  },
  calendarDayText: {
    color: muted,
    fontSize: 12,
    fontWeight: '900',
  },
  calendarDateText: {
    color: ink,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 3,
  },
  calendarDayTextActive: {
    color: bg,
  },
  upcomingGroup: {
    marginTop: 20,
  },
  upcomingGroupHeader: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  upcomingDay: {
    color: ink,
    fontSize: 19,
    fontWeight: '900',
  },
  upcomingDate: {
    color: muted,
    fontSize: 12,
    fontWeight: '900',
  },
  upcomingCard: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 106,
    marginBottom: 10,
    overflow: 'hidden',
  },
  upcomingCardCompact: {
    minHeight: 96,
  },
  upcomingPoster: {
    alignSelf: 'stretch',
    width: 82,
  },
  upcomingPosterCompact: {
    width: 68,
  },
  upcomingPosterImage: {
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
  },
  upcomingCopy: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 12,
  },
  upcomingCopyCompact: {
    paddingHorizontal: 10,
  },
  upcomingShow: {
    color: ink,
    fontSize: 16,
    fontWeight: '900',
  },
  upcomingEpisode: {
    color: '#d7dccf',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 4,
  },
  upcomingMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 9,
  },
  platformPill: {
    backgroundColor: '#252820',
    borderRadius: 11,
    color: gold,
    fontSize: 10,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  upcomingTime: {
    color: muted,
    fontSize: 11,
    fontWeight: '900',
  },
  reminderButton: {
    alignItems: 'center',
    backgroundColor: '#252820',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    marginRight: 12,
    width: 42,
  },
  reminderButtonActive: {
    backgroundColor: accent,
  },
  libraryHero: {
    backgroundColor: panel,
    borderRadius: 8,
    padding: 16,
  },
  libraryKicker: {
    color: gold,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  libraryTitle: {
    color: ink,
    fontSize: 25,
    fontWeight: '900',
    marginTop: 4,
  },
  libraryBody: {
    color: muted,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 8,
  },
  openListsButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: accent,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  openListsText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  libraryFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    marginTop: 12,
  },
  libraryFilter: {
    backgroundColor: panel,
    borderRadius: 16,
    color: muted,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  libraryFilterActive: {
    backgroundColor: gold,
    color: bg,
  },
  libraryList: {
    gap: 10,
    marginTop: 16,
  },
  libraryCard: {
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 118,
    overflow: 'hidden',
  },
  libraryCardCompact: {
    minHeight: 108,
  },
  libraryPoster: {
    alignSelf: 'stretch',
    width: 86,
  },
  libraryPosterCompact: {
    width: 72,
  },
  libraryPosterImage: {
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
  },
  libraryCopy: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    padding: 12,
  },
  libraryTopLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  libraryShowTitle: {
    color: ink,
    flex: 1,
    fontSize: 17,
    fontWeight: '900',
  },
  libraryStatus: {
    backgroundColor: '#252820',
    borderRadius: 10,
    color: gold,
    fontSize: 10,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  libraryStatusDone: {
    color: accent,
  },
  libraryNext: {
    color: '#d7dccf',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 6,
  },
  libraryMeta: {
    color: muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 7,
  },
  listsHero: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  createListButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  createListPanel: {
    backgroundColor: panel,
    borderRadius: 8,
    gap: 10,
    marginTop: 12,
    padding: 14,
  },
  createListTitle: {
    color: ink,
    fontSize: 16,
    fontWeight: '900',
  },
  createListInput: {
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    color: ink,
    fontSize: 14,
    fontWeight: '800',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  createListActions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
  },
  createListCancel: {
    alignItems: 'center',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  createListCancelText: {
    color: muted,
    fontSize: 13,
    fontWeight: '900',
  },
  createListSave: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 16,
  },
  createListSaveText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  listQuickRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  quickListTile: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flex: 1,
    minHeight: 122,
    justifyContent: 'center',
    padding: 12,
  },
  quickListValue: {
    color: ink,
    fontSize: 25,
    fontWeight: '900',
    marginTop: 8,
  },
  quickListLabel: {
    color: muted,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 3,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  customListStack: {
    gap: 10,
  },
  customListCard: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 110,
    overflow: 'hidden',
    paddingRight: 12,
  },
  listPosterStack: {
    height: 110,
    position: 'relative',
    width: 128,
  },
  listPosterSlice: {
    bottom: 12,
    position: 'absolute',
    top: 12,
    width: 62,
  },
  listPosterSliceImage: {
    borderRadius: 8,
  },
  customListCopy: {
    flex: 1,
    paddingHorizontal: 12,
  },
  customListTitle: {
    color: ink,
    fontSize: 17,
    fontWeight: '900',
  },
  customListMeta: {
    color: muted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 5,
  },
  customListArrow: {
    alignItems: 'center',
    backgroundColor: '#252820',
    borderRadius: 8,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  socialListPulse: {
    alignItems: 'center',
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
    padding: 12,
  },
  socialAvatarStack: {
    flexDirection: 'row',
    width: 76,
  },
  socialAvatar: {
    alignItems: 'center',
    backgroundColor: gold,
    borderColor: '#11130f',
    borderRadius: 18,
    borderWidth: 2,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  socialAvatarText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  socialListCopy: {
    flex: 1,
  },
  socialListTitle: {
    color: ink,
    fontSize: 14,
    fontWeight: '900',
  },
  socialListBody: {
    color: muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 3,
  },
  listDetailPosterRow: {
    flexDirection: 'row',
    gap: 10,
    height: 190,
    marginTop: 14,
  },
  listDetailPoster: {
    flex: 1,
  },
  listDetailPosterImage: {
    borderRadius: 8,
  },
  listPrivacyToggle: {
    alignItems: 'center',
    backgroundColor: gold,
    borderRadius: 8,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  listPrivacyText: {
    color: bg,
    fontSize: 12,
    fontWeight: '900',
  },
  listShareCard: {
    backgroundColor: '#11130f',
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    padding: 14,
  },
  listDetailItems: {
    gap: 10,
  },
  listDetailItem: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 12,
    minHeight: 86,
    overflow: 'hidden',
    paddingRight: 12,
  },
  listDetailThumb: {
    alignSelf: 'stretch',
    width: 66,
  },
  listDetailThumbImage: {
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
  },
  notificationsHero: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    padding: 16,
  },
  notificationsBell: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 8,
    height: 54,
    justifyContent: 'center',
    position: 'relative',
    width: 54,
  },
  notificationBellDot: {
    backgroundColor: gold,
    borderColor: panel,
    borderRadius: 6,
    borderWidth: 2,
    height: 12,
    position: 'absolute',
    right: 8,
    top: 8,
    width: 12,
  },
  notificationTabs: {
    flexDirection: 'row',
    gap: 9,
    marginTop: 12,
  },
  markAllReadButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: accent,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    minHeight: 40,
    paddingHorizontal: 12,
  },
  markAllReadText: {
    color: bg,
    fontSize: 13,
    fontWeight: '900',
  },
  notificationTab: {
    backgroundColor: panel,
    borderRadius: 16,
    color: muted,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  notificationTabActive: {
    backgroundColor: gold,
    borderRadius: 16,
    color: bg,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  notificationList: {
    gap: 10,
    marginTop: 16,
  },
  notificationCard: {
    alignItems: 'flex-start',
    backgroundColor: panel,
    borderColor: 'transparent',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    padding: 14,
    position: 'relative',
  },
  notificationAccentBar: {
    backgroundColor: gold,
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 4,
  },
  notificationCardUnread: {
    borderColor: '#34392e',
    backgroundColor: '#1c2018',
  },
  notificationIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  notificationCopy: {
    flex: 1,
    minWidth: 180,
  },
  notificationReadButton: {
    alignItems: 'center',
    backgroundColor: gold,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: 10,
  },
  notificationReadButtonDone: {
    backgroundColor: '#252820',
  },
  notificationReadText: {
    color: bg,
    fontSize: 11,
    fontWeight: '900',
  },
  notificationReadTextDone: {
    color: muted,
  },
  notificationTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  notificationType: {
    color: gold,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  notificationTime: {
    color: muted,
    fontSize: 11,
    fontWeight: '800',
  },
  notificationTitle: {
    color: ink,
    fontSize: 15,
    fontWeight: '900',
    marginTop: 6,
  },
  notificationBody: {
    color: muted,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 4,
  },
  unreadDot: {
    backgroundColor: accent,
    borderRadius: 5,
    height: 10,
    position: 'absolute',
    right: 10,
    top: 10,
    width: 10,
  },
  settingsHero: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 14,
    padding: 16,
  },
  settingsHeroCopy: {
    flex: 1,
  },
  settingsName: {
    color: ink,
    fontSize: 20,
    fontWeight: '900',
  },
  settingsEmail: {
    color: muted,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 4,
  },
  settingsGroup: {
    backgroundColor: panel,
    borderRadius: 8,
    overflow: 'hidden',
  },
  themeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  themeCard: {
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minWidth: 148,
    padding: 12,
  },
  themeCardActive: {
    borderColor: gold,
  },
  themeSwatches: {
    flexDirection: 'row',
    gap: 6,
  },
  themeSwatch: {
    borderColor: '#252820',
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    width: 24,
  },
  themeName: {
    color: muted,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 10,
  },
  themeNameActive: {
    color: ink,
  },
  settingRow: {
    alignItems: 'center',
    borderBottomColor: '#252820',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 72,
    paddingHorizontal: 14,
  },
  settingTitle: {
    color: ink,
    fontSize: 15,
    fontWeight: '900',
  },
  settingValue: {
    color: muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  settingToggle: {
    backgroundColor: '#34392e',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 48,
  },
  settingToggleActive: {
    backgroundColor: accent,
  },
  settingToggleKnob: {
    backgroundColor: muted,
    borderRadius: 11,
    height: 22,
    width: 22,
  },
  settingToggleKnobActive: {
    alignSelf: 'flex-end',
    backgroundColor: bg,
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  serviceTile: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: '#252820',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 54,
    justifyContent: 'center',
    width: '48%',
  },
  serviceTileActive: {
    borderColor: accent,
  },
  serviceText: {
    color: muted,
    fontSize: 13,
    fontWeight: '900',
  },
  serviceTextActive: {
    color: ink,
  },
  signOutButton: {
    alignItems: 'center',
    borderColor: gold,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 22,
    minHeight: 52,
  },
  signOutText: {
    color: gold,
    fontSize: 14,
    fontWeight: '900',
  },
  deleteAccountButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 48,
  },
  deleteAccountText: {
    color: '#e74536',
    fontSize: 13,
    fontWeight: '900',
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    flex: 1,
    justifyContent: 'center',
    padding: 22,
  },
  confirmModal: {
    backgroundColor: '#182014',
    borderColor: '#6f9c2f',
    borderRadius: 8,
    borderWidth: 1,
    maxWidth: 420,
    padding: 20,
    width: '100%',
  },
  confirmTitle: {
    color: '#f8f8f9',
    fontSize: 20,
    fontWeight: '900',
  },
  confirmBody: {
    color: '#d8dfcf',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 10,
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  confirmCancelButton: {
    alignItems: 'center',
    backgroundColor: '#0b1009',
    borderColor: '#48533f',
    borderWidth: 1,
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  confirmCancelText: {
    color: '#f8f8f9',
    fontSize: 14,
    fontWeight: '900',
  },
  confirmDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#e74536',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  confirmDeleteText: {
    color: '#fffaf2',
    fontSize: 14,
    fontWeight: '900',
  },
});
